import React, { useState } from 'react';
import axios from 'axios';

const Vehicle = () => {
    const [licensePlate, setLicensePlate] = useState('');
    const [model, setModel] = useState('');
    const [year, setYear] = useState(0);
    const [batteryCapacity, setBatteryCapacity] = useState(0);
    const [electricType, setElectricType] = useState('');
    const [clientId, setClientId] = useState(0);
    const [message, setMessage] = useState('');

    const handleSubmit = async (event) => {
        event.preventDefault();

        const vehicleData = {
            vehicleId: 0, // Assuming this is auto-generated by the server
            licensePlate,
            model,
            year,
            batteryCapacity,
            electricType,
            clientId,
        };

        try {
            const response = await axios.post('https://localhost:7080/api/Clients/vehicle', vehicleData);
            setMessage(`Vehicle added successfully: ${JSON.stringify(response.data)}`);
            // Optionally reset form fields
            setLicensePlate('');
            setModel('');
            setYear(0);
            setBatteryCapacity(0);
            setElectricType('');
            setClientId(0);
        } catch (error) {
            setMessage(`Error adding vehicle: ${error.response ? error.response.data : error.message}`);
        }
    };

    return (
        <div>
            <h2>Add a New Vehicle</h2>
            <form onSubmit={handleSubmit}>
                <div>
                    <label>License Plate:</label>
                    <input 
                        type="text" 
                        value={licensePlate} 
                        onChange={(e) => setLicensePlate(e.target.value)} 
                        required 
                    />
                </div>
                <div>
                    <label>Model:</label>
                    <input 
                        type="text" 
                        value={model} 
                        onChange={(e) => setModel(e.target.value)} 
                        required 
                    />
                </div>
                <div>
                    <label>Year:</label>
                    <input 
                        type="number" 
                        value={year} 
                        onChange={(e) => setYear(Number(e.target.value))} 
                        required 
                    />
                </div>
                <div>
                    <label>Battery Capacity:</label>
                    <input 
                        type="number" 
                        value={batteryCapacity} 
                        onChange={(e) => setBatteryCapacity(Number(e.target.value))} 
                        required 
                    />
                </div>
                <div>
                    <label>Electric Type:</label>
                    <input 
                        type="text" 
                        value={electricType} 
                        onChange={(e) => setElectricType(e.target.value)} 
                        required 
                    />
                </div>
                <div>
                    <label>Client ID:</label>
                    <input 
                        type="number" 
                        value={clientId} 
                        onChange={(e) => setClientId(Number(e.target.value))} 
                        required 
                    />
                </div>
                <button type="submit">Add Vehicle</button>
            </form>
            {message && <p>{message}</p>}
        </div>
    );
};

export default Vehicle;